In [ ]:
# Initialize a dictionary "emp_info" with below details
# In - emp_info['Tom']
# Out - {'email':'tom_latham019@gmail.com', 'Phone': +1987654321, 'City': 'California'}

# In - emp_info['Kathy']
# Out - {'email':'Kathy019@gmail.com', 'Phone': +17895152351, 'City': 'Florida'}


emp_info ={'Tom':{'email':'tom_latham019@gmail.com', 'Phone': +1987654321, 'City': 'California'}, 'Kathy':{'email':'Kathy019@gmail.com', 'Phone': +17895152351, 'City': 'Florida'}}
a = input('Enter the name: ').capitalize()
print(emp_info.get(a, "This name doesn't exist in the record"))

Enter the name: kathy
{'email': 'Kathy019@gmail.com', 'Phone': 17895152351, 'City': 'Florida'}

In [ ]:
# Create a dictionary out of below inputs
# lst1 = ['emp1', 'emp2', 'emp3']
# emp_key = ['e_name', 'e_id', 'e_sal']
# emp1_val = ['John', 'SG101', '$10,000']
# emp2_val = ['Smith', 'SG102', '$9,000']
# emp3_val = ['Peter', 'SG103', '$9,500']

# Expected Output:- {'emp1':{'e_name':'John', 'e_id':'SG101', 'e_sal':$10,000}, 
#                    'emp2':{'e_name':'Smith', 'e_id':'SG102', 'e_sal':$9,000}, 
#                    'emp3':{'e_name':'Peter', 'e_id':'SG103', 'e_sal':$9,500}}


lst1 = ['emp1', 'emp2', 'emp3']
emp_key = ['e_name', 'e_id', 'e_sal']
emp1_val = ['John', 'SG101', '$10,000']
emp2_val = ['Smith', 'SG102', '$9,000']
emp3_val = ['Peter', 'SG103', '$9,500']

dic={}
dic1= {}
dic2={}
dic3={}
for i in range(3):
  dic1.setdefault(emp_key[i], emp1_val[i])
  dic2.setdefault(emp_key[i],emp2_val[i])
  dic3.setdefault(emp_key[i],emp3_val[i])

lst=[dic1,dic2,dic3]

for j in range(3):
  dic.setdefault(lst1[j],lst[j])

print(dic)

{'emp1': {'e_name': 'John', 'e_id': 'SG101', 'e_sal': '$10,000'}, 'emp2': {'e_name': 'Smith', 'e_id': 'SG102', 'e_sal': '$9,000'}, 'emp3': {'e_name': 'Peter', 'e_id': 'SG103', 'e_sal': '$9,500'}}

In [ ]:
# Access the value of key 'history'

sampleDict = { 
   "class":{ 
      "student":{ 
         "name":"Mike",
         "marks":{ 
            "physics":70,
            "history":80
         }
      }
   }
}

print(sampleDict['class']['student']['marks']['history'])

80

In [ ]:
# Initialize dictionary with default values. Inputs are:-
# employees = ['Kelly', 'Emma', 'John']
# defaults = {"designation": 'Application Developer', "salary": 8000}

#Expected output:- {'Kelly': {'designation': 'Application Developer', 'salary': 8000}, 
#                   'Emma': {'designation': 'Application Developer', 'salary': 8000}, 
#                   'John': {'designation': 'Application Developer', 'salary': 8000}}


employees = ['Kelly', 'Emma', 'John']
defaults = {"designation": 'Application Developer', "salary": 8000}
dic={}
print(dic.fromkeys(employees,defaults))

{'Kelly': {'designation': 'Application Developer', 'salary': 8000}, 'Emma': {'designation': 'Application Developer', 'salary': 8000}, 'John': {'designation': 'Application Developer', 'salary': 8000}}

In [ ]:
# In gene expression, mRNA is transcribed from a DNA template. 
# The 4 nucleotide bases of A, T, C, G corresponds to the U, A, G, C bases of the mRNA. 
# Write a function that returns the mRNA transcript given the sequence of a DNA strand.

# Use a dictionary to provide the mapping of DNA to RNA bases.

def ConvertDNAtomRNA():
 d = {'A': 'U', 'T':'A', 'C':'G', 'G': 'C'}
 op=''
 ip = input("Enter the DNA Strand: ").upper()
 for i in ip:
  op+=d.get(i)
 print(op)
 
ConvertDNAtomRNA()

Enter the DNA Strand: atcc
UAGG

In [ ]:
# Write a function which takes a word as input and returns a dictionary with letters as key and no of time letters are repeated as value.
# In - count_letter('google.com')
# Out - {'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}
def count_letter(p):
 d={}
 ip = input("Enter the name: ")
 lst = list(ip)
 lst1=[]
 for i in range(len(ip)):
  count = ip.count(ip[i])
  lst1.append(count)
 for j in range(len(ip)):
  d.setdefault(lst[j],lst1[j])
 print(d)
 
count_letter()

Enter the name: google.com
{'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}

In [ ]:
# A DNA strand consisting of the 4 nucleotide bases is usually represented with a string of letters: A,T, C, G. 
# Write a function that computes the base composition of a given DNA sequence.

# In - baseComposition("CTATCGGCACCCTTTCAGCA")
# Out - {'A': 4, 'C': 8, 'T': 5,  'G': 3 }


ip = "CTATCGGCACCCTTTCAGCA"

def baseComposition(ip):

 count_A = ip.count('A')
 count_T = ip.count('T')
 count_C = ip.count('C')
 count_G = ip.count('G')

 d={'A':count_A, 'C':count_C, 'T':count_T, 'G':count_G}
 print(d)

baseComposition(ip)

{'A': 4, 'C': 8, 'T': 5, 'G': 3}

In [ ]:
# In - baseComposition("AGT")
# Out - {'A': 1, 'C': 0, 'T': 1,  'G': 1 }


ip1 = "AGT"
baseComposition(ip1)

{'A': 1, 'C': 0, 'T': 1, 'G': 1}

In [ ]:
# [MCQ] Suppose "d" is an empty dictionary, which statement does not assign "d" with {"Name":"Tom"}? 
d2={}
d3={}
d4={}
d1 = {"Name": "Tom" }
d2["Name"] = "Tom"
d3.update({"Name": "Tom" })
d4.setdefault("Name", "Tom")
# 5. None of the above.

# None of above

print(d1,d2,d3,d4)

{'Name': 'Tom'} {'Name': 'Tom'} {'Name': 'Tom'} {'Name': 'Tom'}

In [ ]:
# [MCQ] d = {"a":1, "b":2}. Which of the statements returns [1,2]? 
# 1. d.keys()
# 2. d.values()
# 3. d.items()
# 4. d.popitem()
# 5. None of the above.
d = {"a":1, "b":2}
print(d.keys())
print(list(d.values()))
print(d.items())
print(d.popitem())

# d.values()

dict_keys(['a', 'b'])
[1, 2]
dict_items([('a', 1), ('b', 2)])
('b', 2)

In [ ]:
# [MCQ] Which of the following declarations is not valid for 'dict' type?
# 1. d = {"Name": "Tom" }
# 2. d = { (1,3,4): 4.5 }
# 3. d = { ["First", "Last"]: (1,3) } --------->Not Valid
# 4. d = { 1: 0.4 }
# 5. None of the above

d1 = {"Name": "Tom" }
d2 = { (1,3,4): 4.5 }
# d3 = { ["First", "Last"]: (1,3) }
d4 = { 1: 0.4 }

print(d1,d2,d4)

{'Name': 'Tom'} {(1, 3, 4): 4.5} {1: 0.4}

In [ ]:
# Write a function reverseLookup(dictionary, value) that takes in a dictionary 
# and a value as arguments and returns a sorted list of all keys that contains the value. 
# The function will return an empty list if no match is found.

# In - reverseLookup({'a':1, 'b':2, 'c':2}, 1)
# Out - ['a']
# In - reverseLookup({'a':1, 'b':2, 'c':2}, 2)
# Out - ['b', 'c']
# In - reverseLookup({'a':1, 'b':2, 'c':2}, 3)
# Out - []


def reverseLookup(d,v):
  lst=[]
  for i in d:
    if d[i] == v:
      lst.append(i)
  print(lst)

reverseLookup({'a':1, 'b':2, 'c':2}, 1)
reverseLookup({'a':1, 'b':2, 'c':2}, 2)
reverseLookup({'a':1, 'b':2, 'c':2}, 3)

['a']
['b', 'c']
[]

In [288]:
# Write a function invertDictionary(d) that takes in a dictionary as argument and return a dictionary that inverts the keys and the values of the original dictionary.
# In - invertDictionary({'a':1, 'b':2, 'c':3, 'd':2})
# Out - {1: ['a'], 2: ['b', 'd'], 3: ['c']}

# In - invertDictionary({'a':3, 'b':3, 'c':3})
# Out - {3: ['a', 'c', 'b']}

# In - invertDictionary({'a':2, 'b':1, 'c':2, 'd':1})
# Out - {1: ['b', 'd'], 2: ['a', 'c']}

def invertDictionary(d):
  d1={}
  lst= list(d.keys())
  lst1 =list(d.values())
  for i in range(len(lst)):
    for j in range(len(lst1)):
      d1.setdefault(lst1[i],[]).append(lst[i])
      break
  print(d1)

invertDictionary({'a':'1', 'b':'2', 'c':'3', 'd':'2'})
invertDictionary({'a':'3', 'b':'3', 'c':'3'})
invertDictionary({'a':'2', 'b':'1', 'c':'2', 'd':'1'})

{'1': ['a'], '2': ['b', 'd'], '3': ['c']}
{'3': ['a', 'b', 'c']}
{'2': ['a', 'c'], '1': ['b', 'd']}

In [198]:
# Write a function that converts a sparse vector into a dictionary as described above.
# In - convertVector([1, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 4])
# Out - {0: 1, 3: 2, 7: 3, 12: 4}
# In - convertVector([1, 0, 1 , 0, 2, 0, 1, 0, 0, 1, 0])
# Out - {0: 1, 2: 1, 4: 2, 6: 1, 9: 1}
# In - convertVector([0, 0, 0, 0, 0])
# Out - {}

def convertVector(a):
  d={}
  for i in range(len(a)):
    if a[i] > 0:
      d.setdefault(i,a[i])
  print(d)

convertVector([1, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 4])
convertVector([1, 0, 1 , 0, 2, 0, 1, 0, 0, 1, 0])
convertVector([0, 0, 0, 0, 0])

{0: 1, 3: 2, 7: 3, 12: 4}
{0: 1, 2: 1, 4: 2, 6: 1, 9: 1}
{}

In [226]:
# Write a function that converts a dictionary back to its sparse vector representation.
# In - convertDictionary({0: 1, 3: 2, 7: 3, 12: 4})
# Out - [1, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 4]
# In - convertDictionary({0: 1, 2: 1, 4: 2, 6: 1, 9: 1})
# Out - [1, 0, 1, 0, 2, 0, 1, 0, 0, 1]
# In - convertDictionary({})
# Out - []

def convertDictionary(d):
  lst=[]
  lst1 =list(d.keys())
  lst2 = list(d.values())
  j=0
  if len(d)>0:
    for i in range(lst1[len(lst1)-1]+1):
      if lst1[j] == i:
        lst.append(lst2[j])
        j+=1
      else:
        lst.append(0)
  else:
    pass     

  print(lst)

convertDictionary({0: 1, 3: 2, 7: 3, 12: 4})
convertDictionary({0: 1, 2: 1, 4: 2, 6: 1, 9: 1})
convertDictionary({})

[1, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 4]
[1, 0, 1, 0, 2, 0, 1, 0, 0, 1]
[]

In [263]:
# {# Given a Python dictionary, Change Brad’s salary to 8500
# sampleDict = {
#      'emp1': {'name': 'Jhon', 'salary': 7500},
#      'emp2': {'name': 'Emma', 'salary': 8000},
#      'emp3': {'name': 'Brad', 'salary': 6500}
# }

# Expected Output
# sampleDict = {
#      'emp1': {'name': 'Jhon', 'salary': 7500},
#      'emp2': {'name': 'Emma', 'salary': 8000},
#  'emp3': {'name': 'Brad', 'salary': 8500}

sampleDict = {
     'emp1': {'name': 'Jhon', 'salary': 7500},
     'emp2': {'name': 'Emma', 'salary': 8000},
     'emp3': {'name': 'Brad', 'salary': 6500}
}
 
for i in sampleDict:
  if sampleDict[i]['name'] == 'Brad':
    sampleDict[i]['salary'] = 8500
  else:
    pass

print(sampleDict)

{'emp1': {'name': 'Jhon', 'salary': 7500}, 'emp2': {'name': 'Emma', 'salary': 8000}, 'emp3': {'name': 'Brad', 'salary': 8500}}

In [243]:
# Get the key corresponding to the minimum value from the following dictionary
# sampleDict = {
#   'Physics': 82,
#   'Math': 65,
#   'history': 75
# }

# Expected Output
# Math

sampleDict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}

a = min(sampleDict.values())

for i in sampleDict:
  if sampleDict[i] == a:
    print(i)
  else:
    pass

Math

In [239]:
# Rename key city to location in the following dictionary
# sampleDict = {
#   "name": "Kelly",
#   "age":25,
#   "salary": 8000,
#   "city": "New york"
# }

# Expected Output
# {
#   "name": "Kelly",
#   "age":25,
#   "salary": 8000,
#   "location": "New york"
# }


sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}

sampleDict["Location"]= sampleDict.pop("city")

print(sampleDict)

{'name': 'Kelly', 'age': 25, 'salary': 8000, 'Location': 'New york'}

In [230]:
# Check if a value 200 exists in a dictionary
# sampleDict = {'a': 100, 'b': 200, 'c': 300}

val = 200
d = {'a': 100, 'b': 200, 'c': 300}
for i in list(d.values()):
  if val == i:
    print(True)
    break
  else:
    pass

# Expected Output: True

True

In [237]:
# Delete set of keys from Python Dictionary
# sampleDict = {
#   "name": "Kelly",
#   "age":25,
#   "salary": 8000,
#   "city": "New york"
  
# }
# keysToRemove = ["name", "salary"]

# Expected Output:
# {'city': 'New york', 'age': 25}

sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}

kr = ["name", "salary"]

for i in kr:
  sampleDict.pop(i)

print(sampleDict)

{'age': 25, 'city': 'New york'}